apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default   #demo-project
  source:
    repoURL: 'https://github.com/eoludotun/demo-argocd-kusto-helm'
    targetRevision: HEAD
    path: apps
  destination:
    namespace: app-of-app
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true



