apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/eoludotun/demo-argocd-kusto-helm'
    targetRevision: HEAD
    path: 04-app-of-app
  destination:
    namespace: in-cluster
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
      retry:
        limit: 3
    post:
      helm:
        postRenderer: true

