apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-stage
  namespace: argocd
spec:
  destination:
    namespace: stage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 02-working-with-helm/helm-umbrella-chart/
    repoURL: https://github.com/eoludotun/demo-argocd-kusto-helm
    targetRevision: HEAD
    helm:
      # https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#values-files
      valueFiles:
      - values-stage.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
